#!/bin/sh
#
# macOS codesign wrapper for macdeployqt
#
# Put this in PATH before /usr/bin so that macdeployqt executes it instead of
# the real codesign binary. This makes it possible to add options that are not
# yet supported by macdeployqt.
#
# Copyright (C) 2020 Stefan Hajnoczi <stefanha@jammr.net>
#
# Wahjam is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Wahjam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Wahjam; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

cd "$(dirname $0)"
scriptdir="$(pwd)"
cd - 2>&1 /dev/null

exec /usr/bin/codesign -o runtime --timestamp --entitlements "$scriptdir/qtclient.entitlements" "$@"
